services:
  db:
    image: postgres:16-alpine
    container_name: demo_hotel_db
    environment:
      POSTGRES_DB: demo_hotel
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "55432:5432"
  mailpit:
    image: axllent/mailpit:latest
    container_name: demo_hotel_mailpit
    ports:
      - "8025:8025" # UI
      - "1025:1025" # SMTP
volumes:
  db_data:
