#!/usr/bin/env bash
set -euo pipefail

PORT="${PORT:-8000}"

# Ensure APP_ENV is set and a .env file exists to avoid Dotenv errors in console
export APP_ENV="${APP_ENV:-prod}"
if [ ! -f /app/.env ]; then
  echo "# auto-generated by entrypoint" > /app/.env
fi

echo "[entrypoint] Waiting for database to be ready..."
max_retries=45
for i in $(seq 1 $max_retries); do
  if php docker/wait_for_db.php >/dev/null 2>&1; then
    echo "[entrypoint] Database is available."
    break
  else
    echo "[entrypoint] DB not ready yet, retry $i/$max_retries..."
    php docker/wait_for_db.php || true
    sleep 2
  fi
done

if ! php docker/wait_for_db.php >/dev/null 2>&1; then
  echo "[entrypoint] Database still not reachable after $max_retries retries. Starting anyway."
fi

echo "[entrypoint] Installing PHP dependencies (no-dev, no-scripts)..."
composer install --no-dev --no-scripts --prefer-dist --no-interaction --optimize-autoloader || true

echo "[entrypoint] Running Doctrine migrations..."
php bin/console doctrine:migrations:migrate --no-interaction || true

echo "[entrypoint] Seeding application data (if needed)..."
php bin/console app:ensure-seed || true

echo "[entrypoint] Clearing and warming up cache..."
php bin/console cache:clear --no-warmup || true
php bin/console cache:warmup || true

echo "[entrypoint] Starting PHP server on 0.0.0.0:${PORT}"
exec php -S 0.0.0.0:"${PORT}" -t public public/index.php
